### ISSUE TITLE
scalafmt workflow

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/bebe#22]
@alfonsorr - can you please send me your recommended scalafmt workflow?  Should I run a command before committing?

**Comment by alfonsorr** [comment]
It has
scalafmt that formats the code but not tests
scalafmtAll formats also the tests
scalafmtCheck checks the source is formated ok

and scalafmt Sbt  formats the sbt file

Pass the scalafmtAll previously to upload

**Comment by MrPowers** [comment]
The scalafmt @alfonsorr laid out is working well
