### ISSUE TITLE
Publishing command now broken

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/bebe#34]
@alfonsorr - I can't publish this lib anymore, [see the issue report here](https://github.com/xerial/sbt-sonatype/issues/224).

Any idea how to fix this.  Are you able to publish libs?  Thanks!

**Comment by alfonsorr** [comment]
I will take a look later

**Comment by alfonsorr** [comment]
I see that the plugin is not updated, to the latest version as the issue you linked says, the latest version is 3.9.7. I've updated it.
The CI is prepared to publish or did you do it manually?

**Comment by MrPowers** [comment]
@alfonsorr - sorry, figured this out and forgot to report back.  So, apparently, my Sonatype password just randomly stopped working.  I reset my password on the Sonatype site and the publishing command is working again ;)
